### ISSUE TITLE
ADServicePrincipalName: Remove duplicate code

### ISSUE THREAD

**Issue by johlju** [dsccommunity/ActiveDirectoryDsc#520]
There are some duplicated code that could be removed to simplify the resource.

Instead of calling `Get-ADObject` here we could instead call `Get-TargetResource`. 

https://github.com/PowerShell/ActiveDirectoryDsc/blob/c3c93ba1bc1b8168655cc971474dde277d7c9574/DSCResources/MSFT_ADServicePrincipalName/MSFT_ADServicePrincipalName.psm1#L95

Instead of having this code

https://github.com/PowerShell/ActiveDirectoryDsc/blob/c3c93ba1bc1b8168655cc971474dde277d7c9574/DSCResources/MSFT_ADServicePrincipalName/MSFT_ADServicePrincipalName.psm1#L108-L117

We could potentially move this code to the top of the function and make sure it also handles any duplicate accounts when `Ensure -eq 'Present'`.

https://github.com/PowerShell/ActiveDirectoryDsc/blob/c3c93ba1bc1b8168655cc971474dde277d7c9574/DSCResources/MSFT_ADServicePrincipalName/MSFT_ADServicePrincipalName.psm1#L135-L145

**Comment by dan-hughes** [comment]
Hi @johlju, 

I can take a look at this.

On calling `Get-TargetResource` instead of `Get-ADObject`, what's the most optimal/preferred way of passing ADObject results to the `Set` function? Currently only the `SamAccountNames` are passed in via the `Account` property.
Without the ADObject there is nothing to satisfy the Identity for `Set-ADObject`, which is why it looks to be called again.

On moving the duplicated Remove code, the best option is likely dependent on the outcome of the above, or it get's moved out to a helper function.

Thoughts and direction would be appreciated and I'll get to work.

**Comment by johlju** [comment]
Looking at it now I not sure what I initially thought way back then - looking at it now the code looks good as-is. 🤔 

The only addition we can do to the `Set`-function that I see now is to call `Test`-function at the top of the `Set`-function to see if the state is not desired and only then run the code in the Set-function. This is when for example `Invoke-DscResource` is called with method `Set` it would not try to change anything if there aren't anything to change.  🤔

**Comment by johlju** [comment]
Forgot to answer your question.

> On calling Get-TargetResource instead of Get-ADObject, what's the most optimal/preferred way of passing ADObject results to the Set function?

That wouldn't be possible as you wouldn't be able to easily pass that type through a CIM instance. As soon as one need to pass any typ other than a string, int, etc. it becomes to complicated (if it is even possible) for the effort. 🙂
