### ISSUE TITLE
PowerShell 7.2+ Errors due to Removal of PSDesiredStateConfiguration

### ISSUE THREAD

**Issue by matt2005** [dsccommunity/ActiveDirectoryDsc#669]
PowerShell 7.2 has removed the PSDesiredStateConfigurationModule.
[PowerShell 7.2 Removal of DSC Module](https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-72?view=powershell-7.2#separating-dsc-from-powershell-7-to-enable-future-improvements)

Need to Add PSDesiredStateConfiguration to required modules

**Comment by johlju** [comment]
The reason for the pipeline did not work was because it wasn't using the latest pipeline files from the project Sampler. I updated the files now and the pipeline works again. HQRM Test are using Windows PowerShell to run. 

I think the proposed change in PR #670 that suggests using the v2.0.5 version of PSDesiredStateConfiguration in the example might add a complexity to users still on Windows PowerShell where the built in PSDesiredStateConfiguration can be used. I think we need to take a broader approach if we gonna move this module to PowerShell 7, with proper documentation what works and what does not work.

**Comment by gaelcolas** [comment]
Yeah, and I see little benefit in moving to psdsc 2.0.5
Making it compatible with 3.0.beta1 directly would probably be best.
That does mean converting to class based DSC Resources though.

**Comment by johlju** [comment]
Closing this for now. Another issue need to be opened to track moving to class-based and PS 7.
